"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from que_media.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CawgVerifyDtoTypedDict(TypedDict):
    r"""Options controlling CAWG identity validation behavior during verification."""

    validate_: NotRequired[bool]
    r"""Whether to run CAWG identity validation."""
    require_valid_identity: NotRequired[bool]
    r"""Whether to fail verification if CAWG identity is missing/invalid."""


class CawgVerifyDto(BaseModel):
    r"""Options controlling CAWG identity validation behavior during verification."""

    validate_: Annotated[Optional[bool], pydantic.Field(alias="validate")] = True
    r"""Whether to run CAWG identity validation."""

    require_valid_identity: Optional[bool] = False
    r"""Whether to fail verification if CAWG identity is missing/invalid."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["validate", "require_valid_identity"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CawgVerifyDto.model_rebuild()
except NameError:
    pass
