"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .signerrefdto import SignerRefDto, SignerRefDtoTypedDict
from enum import Enum
from pydantic import Discriminator, Tag, model_serializer
from que_media.types import BaseModel, UNSET_SENTINEL
from que_media.utils import get_discriminator
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class TypeSeparate(str, Enum):
    SEPARATE = "separate"


class SignerSeparateTypedDict(TypedDict):
    type: TypeSeparate
    signer: SignerRefDtoTypedDict
    r"""Reference to credentials for signing."""


class SignerSeparate(BaseModel):
    type: TypeSeparate

    signer: SignerRefDto
    r"""Reference to credentials for signing."""


class TypeUseMainSigner(str, Enum):
    USE_MAIN_SIGNER = "use_main_signer"


class SignerUseMainSignerTypedDict(TypedDict):
    type: TypeUseMainSigner


class SignerUseMainSigner(BaseModel):
    type: TypeUseMainSigner


SignerTypedDict = TypeAliasType(
    "SignerTypedDict", Union[SignerUseMainSignerTypedDict, SignerSeparateTypedDict]
)


Signer = Annotated[
    Union[
        Annotated[SignerUseMainSigner, Tag("use_main_signer")],
        Annotated[SignerSeparate, Tag("separate")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]


class SigningAlg(str, Enum):
    r"""Algorithm used for the CAWG identity signature."""

    ED25519 = "ed25519"
    ES256 = "es256"
    ES384 = "es384"
    PS256 = "ps256"


class CawgIdentityDtoTypedDict(TypedDict):
    r"""Configuration to add a CAWG identity assertion during signing. Presence of this object enables CAWG."""

    signer: NotRequired[SignerTypedDict]
    signing_alg: NotRequired[SigningAlg]
    r"""Algorithm used for the CAWG identity signature."""
    referenced_assertions: NotRequired[List[str]]
    r"""Assertion labels that the identity assertion should reference."""
    timestamper: NotRequired[str]
    r"""Timestamper to use (\"digicert\" or \"custom:<url>\")."""


class CawgIdentityDto(BaseModel):
    r"""Configuration to add a CAWG identity assertion during signing. Presence of this object enables CAWG."""

    signer: Optional[Signer] = None

    signing_alg: Optional[SigningAlg] = SigningAlg.ED25519
    r"""Algorithm used for the CAWG identity signature."""

    referenced_assertions: Optional[List[str]] = None
    r"""Assertion labels that the identity assertion should reference."""

    timestamper: Optional[str] = None
    r"""Timestamper to use (\"digicert\" or \"custom:<url>\")."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["signer", "signing_alg", "referenced_assertions", "timestamper"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
