"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import Discriminator, Tag
from que_media.types import BaseModel
from que_media.utils import get_discriminator
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class TypeLocal(str, Enum):
    LOCAL = "local"


class SignerRefDtoLocalTypedDict(TypedDict):
    type: TypeLocal
    cert_path: str
    key_path: str


class SignerRefDtoLocal(BaseModel):
    type: TypeLocal

    cert_path: str

    key_path: str


class TypeEnv(str, Enum):
    ENV = "env"


class SignerRefDtoEnvTypedDict(TypedDict):
    type: TypeEnv
    cert_var: str
    key_var: str


class SignerRefDtoEnv(BaseModel):
    type: TypeEnv

    cert_var: str

    key_var: str


SignerRefDtoTypedDict = TypeAliasType(
    "SignerRefDtoTypedDict", Union[SignerRefDtoEnvTypedDict, SignerRefDtoLocalTypedDict]
)
r"""Reference to credentials for signing."""


SignerRefDto = Annotated[
    Union[
        Annotated[SignerRefDtoEnv, Tag("env")],
        Annotated[SignerRefDtoLocal, Tag("local")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
r"""Reference to credentials for signing."""
