"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .queerror import QueError
from typing import Any, TYPE_CHECKING

from que_media.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .no_response_error import NoResponseError
    from .problemresponse_error import ProblemResponseError, ProblemResponseErrorData
    from .quedefaulterror import QueDefaultError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "NoResponseError",
    "ProblemResponseError",
    "ProblemResponseErrorData",
    "QueDefaultError",
    "QueError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "NoResponseError": ".no_response_error",
    "ProblemResponseError": ".problemresponse_error",
    "ProblemResponseErrorData": ".problemresponse_error",
    "QueDefaultError": ".quedefaulterror",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
